version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: thalysom_mysql_projeto

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eclipse_net
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app123

    ports:
      - "3306:3306"

    volumes:
      - eclipse_data:/var/lib/mysql

volumes:
  eclipse_data: